sonar.projectKey=jeffgicharu_wallet-api
sonar.projectName=Wallet API
sonar.organization=jeffgicharu

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# JaCoCo coverage report
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclude generated code and config
sonar.exclusions=**/config/**,**/dto/**,**/enums/**,**/entity/**

# Quality gate thresholds
sonar.qualitygate.wait=true
