-- Baseline schema (issue #3). This is the pre-Flyway schema exactly as
-- Hibernate's ddl-auto=update had been generating it, captured via
-- Hibernate's PostgreSQL schema export. It deliberately does NOT include
-- the users.role column: that column was introduced by issue #2 and is
-- applied as a separate migration (V2). Keeping the baseline equal to the
-- already-deployed schema lets an existing database be adopted with
-- baseline-on-migrate at version 1 (V1 skipped, V2 onward applied) while
-- a fresh database runs V1 then V2 to reach the same state.

create table users (
    failed_pin_attempts integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    pin_locked_until timestamp(6),
    phone_number varchar(15) not null unique,
    email varchar(100) not null unique,
    full_name varchar(100) not null,
    password varchar(255) not null,
    pin varchar(255) not null,
    primary key (id)
);

create table wallets (
    active boolean not null,
    balance numeric(15,2) not null,
    currency varchar(3) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    user_id bigint not null unique,
    version bigint,
    primary key (id)
);

create table transactions (
    amount numeric(15,2) not null,
    fee numeric(15,2),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    receiver_wallet_id bigint,
    sender_wallet_id bigint,
    status varchar(20) not null check (status in ('PENDING','COMPLETED','FAILED','REVERSED')),
    type varchar(20) not null check (type in ('DEPOSIT','WITHDRAWAL','TRANSFER','FEE')),
    reference varchar(50) not null unique,
    description varchar(255),
    primary key (id)
);

create table ledger_entries (
    amount numeric(15,2) not null,
    balance_after numeric(15,2) not null,
    balance_before numeric(15,2) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    transaction_id bigint not null,
    wallet_id bigint not null,
    entry_type varchar(10) not null check (entry_type in ('DEBIT','CREDIT')),
    primary key (id)
);

create table audit_logs (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    action varchar(30) not null,
    target_type varchar(30) not null,
    target_id varchar(50) not null,
    actor varchar(100) not null,
    detail varchar(500),
    ip_address varchar(255),
    primary key (id)
);

create index idx_audit_target on audit_logs (target_type, target_id);
create index idx_audit_actor on audit_logs (actor);
create index idx_ledger_wallet on ledger_entries (wallet_id);
create index idx_ledger_txn on ledger_entries (transaction_id);
create index idx_txn_sender on transactions (sender_wallet_id);
create index idx_txn_receiver on transactions (receiver_wallet_id);
create index idx_txn_created on transactions (created_at);

alter table if exists ledger_entries add constraint fk_ledger_transaction foreign key (transaction_id) references transactions;
alter table if exists ledger_entries add constraint fk_ledger_wallet foreign key (wallet_id) references wallets;
alter table if exists transactions add constraint fk_txn_receiver_wallet foreign key (receiver_wallet_id) references wallets;
alter table if exists transactions add constraint fk_txn_sender_wallet foreign key (sender_wallet_id) references wallets;
alter table if exists wallets add constraint fk_wallet_user foreign key (user_id) references users;
